# Generated by Django 2.0.1 on 2019-05-12 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='status_com',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
